""" Flask application config
HINT: in future this has to be in .gitignore and has to be generated generated by the host
"""

"""
This is how you generate a secret key:
>>> import os
>>> os.urandom(24)
"""


class DevelopmentConfig(object):
    SECRET_KEY =\
        '\xf0\xc3\r\x0b\xa7\x1f\xbaz=(\xba\xc6\xda\xccWB\xb9\xfb\x01\x87f\x99\x90U'

    # Flask-SQLAlchemy settings
    SQLALCHEMY_DATABASE_URI = 'sqlite:///docsign.sqlite'  # File-based SQL database
    SQLALCHEMY_TRACK_MODIFICATIONS = False  # Avoids SQLAlchemy warning

    DEBUG = True
    CACHE_TYPE = "simple"
    CACHE_DEFAULT_TIMEOUT = 300
